version: '3'
services:
  openid-connect-server:
    image: killmenot/qewd-server:tests
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/qewd/mapped
    networks:
      ripple:
        ipv4_address: 10.5.0.2

  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - openid-connect-server
    networks:
      ripple:
        ipv4_address: 10.5.0.3

networks:
  ripple:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

# docker-compose -f docker-compose.test.yml up
# docker-compose -f docker-compose.test.yml down --rmi local