version: '3'
services:
  openid-connect-server:
    container_name: openid-connect-server-container
    image: killmenot/qewd-server:tests
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/qewd/mapped
    networks:
      ripple:
        ipv4_address: 10.5.0.2

  sut:
    build:
      context: .
      dockerfile: spec/Dockerfile
    environment:
      - CONTAINER_NAME=openid-connect-server-container
    depends_on:
      - openid-connect-server
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      ripple:
        ipv4_address: 10.5.0.3

networks:
  ripple:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16